# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GenshMain.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(461, 949)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 291, 47))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.le_search = QtWidgets.QLineEdit(self.layoutWidget)
        self.le_search.setObjectName("le_search")
        self.gridLayout_2.addWidget(self.le_search, 0, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 130, 311, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_characters = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_characters.setFont(font)
        self.label_characters.setObjectName("label_characters")
        self.gridLayout_3.addWidget(self.label_characters, 0, 0, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(240, 60, 231, 61))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_weapons = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_weapons.setFont(font)
        self.label_weapons.setObjectName("label_weapons")
        self.gridLayout.addWidget(self.label_weapons, 0, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 2, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 2, 0, 1, 1)
        self.label_elements = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_elements.setFont(font)
        self.label_elements.setObjectName("label_elements")
        self.gridLayout.addWidget(self.label_elements, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.gridLayout_5.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(300, 0, 121, 53))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_filters = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_filters.setFont(font)
        self.label_filters.setObjectName("label_filters")
        self.gridLayout_4.addWidget(self.label_filters, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.layoutWidget4 = QtWidgets.QWidget(Dialog)
        self.layoutWidget4.setGeometry(QtCore.QRect(310, 120, 95, 41))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.but_show = QtWidgets.QPushButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.but_show.setFont(font)
        self.but_show.setObjectName("but_show")
        self.gridLayout_6.addWidget(self.but_show, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.le_search.setText(_translate("Dialog", "Search"))
        self.label_characters.setText(_translate("Dialog", "Characters"))
        self.label_weapons.setText(_translate("Dialog", "Weapons"))
        self.label_elements.setText(_translate("Dialog", "Elements"))
        self.label_filters.setText(_translate("Dialog", "Filters"))
        self.but_show.setText(_translate("Dialog", "Show"))

