# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'genshin_pyqt.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1898, 920)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.le_search = QtWidgets.QLineEdit(self.centralwidget)
        self.le_search.setGeometry(QtCore.QRect(20, 70, 471, 31))
        self.le_search.setText("")
        self.le_search.setObjectName("le_search")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(50, 210, 471, 611))
        self.listWidget.setObjectName("listWidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(530, 130, 155, 59))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.btn_show = QtWidgets.QPushButton(self.centralwidget)
        self.btn_show.setGeometry(QtCore.QRect(680, 110, 155, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_show.setFont(font)
        self.btn_show.setObjectName("btn_show")
        self.label_characters = QtWidgets.QLabel(self.centralwidget)
        self.label_characters.setGeometry(QtCore.QRect(1540, 90, 191, 59))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_characters.setFont(font)
        self.label_characters.setObjectName("label_characters")
        self.label_search = QtWidgets.QLabel(self.centralwidget)
        self.label_search.setGeometry(QtCore.QRect(20, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_search.setFont(font)
        self.label_search.setObjectName("label_search")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(970, 210, 341, 611))
        self.textBrowser.setObjectName("textBrowser")
        self.btn_download = QtWidgets.QPushButton(self.centralwidget)
        self.btn_download.setGeometry(QtCore.QRect(620, 870, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_download.setFont(font)
        self.btn_download.setObjectName("btn_download")
        self.label_image = QtWidgets.QLabel(self.centralwidget)
        self.label_image.setGeometry(QtCore.QRect(580, 210, 321, 591))
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(640, 20, 221, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_elements = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_elements.setFont(font)
        self.label_elements.setObjectName("label_elements")
        self.horizontalLayout.addWidget(self.label_elements)
        self.label_weapons = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_weapons.setFont(font)
        self.label_weapons.setObjectName("label_weapons")
        self.horizontalLayout.addWidget(self.label_weapons)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(640, 60, 221, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cb_elements = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_elements.setObjectName("cb_elements")
        self.horizontalLayout_2.addWidget(self.cb_elements)
        self.cb_weapons = QtWidgets.QComboBox(self.layoutWidget1)
        self.cb_weapons.setObjectName("cb_weapons")
        self.horizontalLayout_2.addWidget(self.cb_weapons)
        self.listWidget_2 = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget_2.setGeometry(QtCore.QRect(1430, 210, 421, 611))
        self.listWidget_2.setObjectName("listWidget_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_show.setText(_translate("MainWindow", "Show"))
        self.label_characters.setText(_translate("MainWindow", "Characters"))
        self.label_search.setText(_translate("MainWindow", "Search"))
        self.btn_download.setText(_translate("MainWindow", "Download information"))
        self.label_elements.setText(_translate("MainWindow", "Elements"))
        self.label_weapons.setText(_translate("MainWindow", "Weapons"))

