# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gensh0.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1004, 651)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 5, 1, 1)
        self.label_characters = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_characters.setFont(font)
        self.label_characters.setObjectName("label_characters")
        self.gridLayout.addWidget(self.label_characters, 0, 8, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(False)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 8, 9, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 6, 1, 1)
        self.btn_show = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_show.setFont(font)
        self.btn_show.setObjectName("btn_show")
        self.gridLayout.addWidget(self.btn_show, 1, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 7, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 6, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setObjectName("btn6")
        self.gridLayout_2.addWidget(self.btn6, 2, 2, 1, 1)
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setObjectName("btn4")
        self.gridLayout_2.addWidget(self.btn4, 2, 0, 1, 1)
        self.btn8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn8.setObjectName("btn8")
        self.gridLayout_2.addWidget(self.btn8, 3, 1, 1, 1)
        self.btn14 = QtWidgets.QPushButton(self.centralwidget)
        self.btn14.setObjectName("btn14")
        self.gridLayout_2.addWidget(self.btn14, 5, 1, 1, 1)
        self.btn15 = QtWidgets.QPushButton(self.centralwidget)
        self.btn15.setObjectName("btn15")
        self.gridLayout_2.addWidget(self.btn15, 5, 2, 1, 1)
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setObjectName("btn5")
        self.gridLayout_2.addWidget(self.btn5, 2, 1, 1, 1)
        self.btn10 = QtWidgets.QPushButton(self.centralwidget)
        self.btn10.setObjectName("btn10")
        self.gridLayout_2.addWidget(self.btn10, 4, 0, 1, 1)
        self.btn11 = QtWidgets.QPushButton(self.centralwidget)
        self.btn11.setObjectName("btn11")
        self.gridLayout_2.addWidget(self.btn11, 4, 1, 1, 1)
        self.btn12 = QtWidgets.QPushButton(self.centralwidget)
        self.btn12.setObjectName("btn12")
        self.gridLayout_2.addWidget(self.btn12, 4, 2, 1, 1)
        self.btn7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn7.setObjectName("btn7")
        self.gridLayout_2.addWidget(self.btn7, 3, 0, 1, 1)
        self.btn9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn9.setObjectName("btn9")
        self.gridLayout_2.addWidget(self.btn9, 3, 2, 1, 1)
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setObjectName("btn1")
        self.gridLayout_2.addWidget(self.btn1, 1, 0, 1, 1)
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setObjectName("btn2")
        self.gridLayout_2.addWidget(self.btn2, 1, 1, 1, 1)
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setObjectName("btn3")
        self.gridLayout_2.addWidget(self.btn3, 1, 2, 1, 1)
        self.btn13 = QtWidgets.QPushButton(self.centralwidget)
        self.btn13.setObjectName("btn13")
        self.gridLayout_2.addWidget(self.btn13, 5, 0, 1, 1)
        self.btn16 = QtWidgets.QPushButton(self.centralwidget)
        self.btn16.setObjectName("btn16")
        self.gridLayout_2.addWidget(self.btn16, 6, 0, 1, 1)
        self.btn17 = QtWidgets.QPushButton(self.centralwidget)
        self.btn17.setObjectName("btn17")
        self.gridLayout_2.addWidget(self.btn17, 6, 1, 1, 1)
        self.btn18 = QtWidgets.QPushButton(self.centralwidget)
        self.btn18.setObjectName("btn18")
        self.gridLayout_2.addWidget(self.btn18, 6, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 8, 9, 1)
        self.le_search = QtWidgets.QLineEdit(self.centralwidget)
        self.le_search.setText("")
        self.le_search.setObjectName("le_search")
        self.gridLayout.addWidget(self.le_search, 0, 0, 1, 4)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 9, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 9, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cb_elements = QtWidgets.QComboBox(self.centralwidget)
        self.cb_elements.setObjectName("cb_elements")
        self.gridLayout_3.addWidget(self.cb_elements, 2, 0, 1, 1)
        self.cb_weapons = QtWidgets.QComboBox(self.centralwidget)
        self.cb_weapons.setObjectName("cb_weapons")
        self.gridLayout_3.addWidget(self.cb_weapons, 2, 1, 1, 1)
        self.label_elements = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_elements.setFont(font)
        self.label_elements.setObjectName("label_elements")
        self.gridLayout_3.addWidget(self.label_elements, 1, 0, 1, 1)
        self.label_weapons = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_weapons.setFont(font)
        self.label_weapons.setObjectName("label_weapons")
        self.gridLayout_3.addWidget(self.label_weapons, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 4, 5, 3)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(False)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 9, 9, 1, 1)
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setObjectName("btn_search")
        self.gridLayout.addWidget(self.btn_search, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 1, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.gridLayout.addWidget(self.listWidget, 6, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_characters.setText(_translate("MainWindow", "Characters"))
        self.btn_show.setText(_translate("MainWindow", "Show"))
        self.btn6.setText(_translate("MainWindow", "Lisa"))
        self.btn4.setText(_translate("MainWindow", "Kazuha"))
        self.btn8.setText(_translate("MainWindow", "Qiqi"))
        self.btn14.setText(_translate("MainWindow", "Bennet"))
        self.btn15.setText(_translate("MainWindow", "Xingqiu"))
        self.btn5.setText(_translate("MainWindow", "Kaeya"))
        self.btn10.setText(_translate("MainWindow", "Klee"))
        self.btn11.setText(_translate("MainWindow", "Xiao"))
        self.btn12.setText(_translate("MainWindow", "Razor"))
        self.btn7.setText(_translate("MainWindow", "Barbara"))
        self.btn9.setText(_translate("MainWindow", "Zhongli"))
        self.btn1.setText(_translate("MainWindow", "Diluc"))
        self.btn2.setText(_translate("MainWindow", "Taraglia"))
        self.btn3.setText(_translate("MainWindow", "Keqing"))
        self.btn13.setText(_translate("MainWindow", "Albedo"))
        self.btn16.setText(_translate("MainWindow", "Chongyun"))
        self.btn17.setText(_translate("MainWindow", "Venti"))
        self.btn18.setText(_translate("MainWindow", "Ningguang"))
        self.label_elements.setText(_translate("MainWindow", "Elements"))
        self.label_weapons.setText(_translate("MainWindow", "Weapons"))
        self.label_13.setText(_translate("MainWindow", "                        "))
        self.btn_search.setText(_translate("MainWindow", "Search"))
        self.label_14.setText(_translate("MainWindow", "                                                                "))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.setSortingEnabled(__sortingEnabled)

